/**
 * Additional startup resources data
 *
 * This file contains additional startup resources that can be used
 * throughout the application without changing any UI/UX components.
 *
 * These resources follow the exact same data structure as existing resources
 * and can be merged with existing resource collections.
 */

export const additionalGuides = [
  {
    id: "guide-7",
    title: "Startup Legal Essentials",
    type: "guide",
    format: "pdf",
    thumbnail: "/abstract-geometric-shapes.png",
    description: "Essential legal knowledge every founder needs to know when starting a business in Singapore.",
    author: "Legal Team at GrowthLab",
    date: "Apr 12, 2025",
    readTime: "18 min read",
    categories: ["Legal", "Compliance"],
    topics: ["Incorporation", "IP Protection", "Contracts"],
    featured: false,
    popular: true,
  },
  {
    id: "guide-8",
    title: "B2B Sales Playbook for Startups",
    type: "guide",
    format: "pdf",
    thumbnail: "/rising-tide-startups.png",
    description: "A comprehensive guide to building and scaling B2B sales for early-stage startups.",
    author: "Sales Team at GrowthLab",
    date: "Mar 28, 2025",
    readTime: "22 min read",
    categories: ["Sales", "Growth"],
    topics: ["Lead Generation", "Sales Process", "Enterprise Deals"],
    featured: true,
    popular: false,
  },
  {
    id: "guide-9",
    title: "Startup Hiring Guide",
    type: "guide",
    format: "pdf",
    thumbnail: "/collaborative-growth.png",
    description: "How to build your dream team from first hire to scaling your organization.",
    author: "HR Team at GrowthLab",
    date: "Mar 15, 2025",
    readTime: "16 min read",
    categories: ["Team", "Hiring"],
    topics: ["Recruitment", "Culture", "Compensation"],
    featured: false,
    popular: true,
  },
]

export const additionalTemplates = [
  {
    id: "template-7",
    title: "Startup Budget Template",
    type: "template",
    format: "xlsx",
    thumbnail: "/abstract-geometric-shapes.png",
    description: "A comprehensive budget template for early-stage startups with expense tracking.",
    author: "Finance Team at GrowthLab",
    date: "Apr 5, 2025",
    readTime: "8 min setup",
    categories: ["Finance", "Planning"],
    topics: ["Budget", "Expense Tracking", "Runway"],
    featured: false,
    popular: true,
  },
  {
    id: "template-8",
    title: "Product Roadmap Template",
    type: "template",
    format: "pptx",
    thumbnail: "/rising-tide-startups.png",
    description: "A visual product roadmap template to plan and communicate your product strategy.",
    author: "Product Team at GrowthLab",
    date: "Mar 22, 2025",
    readTime: "10 min setup",
    categories: ["Product", "Planning"],
    topics: ["Roadmap", "Strategy", "Development"],
    featured: true,
    popular: false,
  },
  {
    id: "template-9",
    title: "Customer Interview Script",
    type: "template",
    format: "docx",
    thumbnail: "/collaborative-growth.png",
    description: "A customizable script for conducting effective customer interviews.",
    author: "UX Team at GrowthLab",
    date: "Mar 10, 2025",
    readTime: "5 min setup",
    categories: ["Research", "Customer Development"],
    topics: ["Interviews", "User Research", "Validation"],
    featured: false,
    popular: true,
  },
]

export const additionalVideos = [
  {
    id: "video-7",
    title: "Startup Funding in Southeast Asia",
    type: "video",
    format: "mp4",
    thumbnail: "/abstract-letter-jt.png",
    description: "An overview of the funding landscape in Southeast Asia with insights from top VCs.",
    author: "Investment Team at GrowthLab",
    date: "Apr 8, 2025",
    readTime: "32 min watch",
    categories: ["Funding", "Investment"],
    topics: ["VC Funding", "Angel Investment", "Regional Trends"],
    featured: true,
    popular: true,
  },
  {
    id: "video-8",
    title: "Product-Led Growth Strategies",
    type: "video",
    format: "mp4",
    thumbnail: "/abstract-ms-flow.png",
    description: "Learn how to implement product-led growth strategies for your SaaS startup.",
    author: "Growth Team at GrowthLab",
    date: "Mar 25, 2025",
    readTime: "28 min watch",
    categories: ["Growth", "Product"],
    topics: ["PLG", "User Onboarding", "Activation"],
    featured: false,
    popular: true,
  },
  {
    id: "video-9",
    title: "Startup Metrics That Matter",
    type: "webinar",
    format: "mp4",
    thumbnail: "/abstract-geometric-shapes.png",
    description: "A deep dive into the key metrics every startup founder should track and optimize.",
    author: "Analytics Team at GrowthLab",
    date: "Mar 18, 2025",
    readTime: "40 min watch",
    categories: ["Analytics", "Growth"],
    topics: ["KPIs", "Data Analysis", "Growth Metrics"],
    featured: false,
    popular: false,
  },
]

export const additionalWebinars = [
  {
    id: "webinar-7",
    title: "Scaling Engineering Teams",
    type: "webinar",
    format: "mp4",
    thumbnail: "/abstract-ms-flow.png",
    description: "Best practices for scaling engineering teams from 5 to 50 engineers.",
    author: "Engineering Team at GrowthLab",
    date: "Apr 15, 2025",
    readTime: "50 min watch",
    categories: ["Engineering", "Team"],
    topics: ["Technical Leadership", "Hiring Engineers", "Engineering Culture"],
    featured: false,
    popular: true,
  },
  {
    id: "webinar-8",
    title: "International Expansion Strategies",
    type: "webinar",
    format: "mp4",
    thumbnail: "/rising-tide-startups.png",
    description: "How to expand your startup internationally with lessons from successful companies.",
    author: "Global Team at GrowthLab",
    date: "Apr 2, 2025",
    readTime: "55 min watch",
    categories: ["Growth", "International"],
    topics: ["Market Entry", "Localization", "Global Operations"],
    featured: true,
    popular: false,
  },
  {
    id: "webinar-9",
    title: "AI for Startups",
    type: "webinar",
    format: "mp4",
    thumbnail: "/collaborative-growth.png",
    description: "Practical applications of AI for early-stage startups with limited resources.",
    author: "Tech Team at GrowthLab",
    date: "Mar 20, 2025",
    readTime: "45 min watch",
    categories: ["Technology", "AI"],
    topics: ["Machine Learning", "AI Tools", "Implementation"],
    featured: false,
    popular: true,
  },
]

export const additionalResourceCategories = [
  {
    id: "category-legal",
    name: "Legal",
    description: "Legal resources for startups including incorporation, IP, and compliance.",
    count: 12,
    icon: "scale",
  },
  {
    id: "category-sales",
    name: "Sales",
    description: "Resources to help you build and scale your sales process.",
    count: 15,
    icon: "trending-up",
  },
  {
    id: "category-engineering",
    name: "Engineering",
    description: "Technical resources for building and scaling your product.",
    count: 18,
    icon: "code",
  },
  {
    id: "category-international",
    name: "International",
    description: "Resources for expanding your startup globally.",
    count: 10,
    icon: "globe",
  },
]

export const additionalResourceTopics = [
  "Incorporation",
  "IP Protection",
  "Contracts",
  "Lead Generation",
  "Sales Process",
  "Enterprise Deals",
  "Recruitment",
  "Culture",
  "Compensation",
  "Budget",
  "Expense Tracking",
  "Runway",
  "Roadmap",
  "Strategy",
  "Development",
  "Interviews",
  "User Research",
  "Validation",
  "VC Funding",
  "Angel Investment",
  "Regional Trends",
  "PLG",
  "User Onboarding",
  "Activation",
  "KPIs",
  "Data Analysis",
  "Growth Metrics",
  "Technical Leadership",
  "Hiring Engineers",
  "Engineering Culture",
  "Market Entry",
  "Localization",
  "Global Operations",
  "Machine Learning",
  "AI Tools",
  "Implementation",
]

// Helper function to merge with existing resources without changing UI/UX
export function mergeWithExistingResources(existingResources: any[], additionalResources: any[]): any[] {
  return [...existingResources, ...additionalResources]
}
