/**
 * Additional cross-audience resources
 *
 * These resources are valuable for multiple audience types (startups, investors, and students)
 * without changing any UI/UX components.
 */

export const crossAudienceResources = [
  {
    id: "cross-guide-1",
    title: "Singapore Startup Ecosystem Guide",
    type: "guide",
    format: "pdf",
    thumbnail: "/enterprise-singapore-building.png",
    description: "A comprehensive guide to the Singapore startup ecosystem, support programs, and resources.",
    author: "Ecosystem Team at GrowthLab",
    date: "Apr 25, 2025",
    readTime: "40 min read",
    categories: ["Ecosystem", "Singapore"],
    topics: ["Support Programs", "Government Initiatives", "Startup Community"],
    featured: true,
    popular: true,
    targetAudience: ["startups", "investors", "students"],
  },
  {
    id: "cross-guide-2",
    title: "Emerging Technology Trends Report",
    type: "guide",
    format: "pdf",
    thumbnail: "/AI-Healthcare-Integration.png",
    description: "Analysis of emerging technology trends and their impact on various industries.",
    author: "Research Team at GrowthLab",
    date: "Apr 20, 2025",
    readTime: "35 min read",
    categories: ["Technology", "Trends"],
    topics: ["AI", "Blockchain", "IoT", "Emerging Tech"],
    featured: true,
    popular: true,
    targetAudience: ["startups", "investors", "students"],
  },
  {
    id: "cross-template-1",
    title: "Startup Valuation Calculator",
    type: "template",
    format: "xlsx",
    thumbnail: "/financial-projection-growth.png",
    description: "A comprehensive tool for calculating startup valuations using multiple methodologies.",
    author: "Finance Team at GrowthLab",
    date: "Apr 22, 2025",
    readTime: "20 min setup",
    categories: ["Valuation", "Finance"],
    topics: ["Valuation Methods", "Financial Modeling", "Investment"],
    featured: true,
    popular: true,
    targetAudience: ["startups", "investors", "students"],
  },
  {
    id: "cross-template-2",
    title: "Networking Event Planning Template",
    type: "template",
    format: "docx",
    thumbnail: "/virtual-networking-event.png",
    description: "A template for planning and organizing successful networking events.",
    author: "Events Team at GrowthLab",
    date: "Apr 18, 2025",
    readTime: "15 min setup",
    categories: ["Networking", "Events"],
    topics: ["Event Planning", "Community Building", "Networking"],
    featured: false,
    popular: true,
    targetAudience: ["startups", "investors", "students"],
  },
  {
    id: "cross-video-1",
    title: "Startup Funding Landscape in Southeast Asia",
    type: "video",
    format: "mp4",
    thumbnail: "/interconnected-fintech.png",
    description: "An overview of the funding landscape in Southeast Asia with insights from investors and founders.",
    author: "Investment Team at GrowthLab",
    date: "Apr 23, 2025",
    readTime: "50 min watch",
    categories: ["Funding", "Investment"],
    topics: ["Funding Landscape", "Investor Insights", "Regional Trends"],
    featured: true,
    popular: true,
    targetAudience: ["startups", "investors", "students"],
  },
  {
    id: "cross-webinar-1",
    title: "Building Sustainable Startups",
    type: "webinar",
    format: "mp4",
    thumbnail: "/green-path-logistics.png",
    description: "How to build environmentally and socially sustainable startups.",
    author: "Sustainability Team at GrowthLab",
    date: "Apr 20, 2025",
    readTime: "75 min watch",
    categories: ["Sustainability", "Social Impact"],
    topics: ["ESG", "Impact Investing", "Sustainable Business Models"],
    featured: true,
    popular: false,
    targetAudience: ["startups", "investors", "students"],
  },
]
