/**
 * Additional investor-specific resources
 *
 * These resources are specifically designed for investors
 * without changing any UI/UX components.
 */

export const investorSpecificResources = [
  {
    id: "investor-guide-1",
    title: "Due Diligence Checklist for Early-Stage Investments",
    type: "guide",
    format: "pdf",
    thumbnail: "/investor-meeting.png",
    description: "A comprehensive checklist for conducting due diligence on early-stage startups.",
    author: "Investment Team at GrowthLab",
    date: "Apr 20, 2025",
    readTime: "30 min read",
    categories: ["Investment", "Due Diligence"],
    topics: ["Evaluation", "Risk Assessment", "Investment Criteria"],
    featured: true,
    popular: true,
    targetAudience: ["investors"],
  },
  {
    id: "investor-guide-2",
    title: "Southeast Asian Startup Ecosystem Report",
    type: "guide",
    format: "pdf",
    thumbnail: "/singapore-startup-collaboration.png",
    description: "An in-depth analysis of the startup ecosystem in Southeast Asia.",
    author: "Research Team at GrowthLab",
    date: "Apr 15, 2025",
    readTime: "45 min read",
    categories: ["Market Research", "Investment"],
    topics: ["Market Trends", "Ecosystem Analysis", "Regional Insights"],
    featured: true,
    popular: false,
    targetAudience: ["investors"],
  },
  {
    id: "investor-template-1",
    title: "Investment Memo Template",
    type: "template",
    format: "docx",
    thumbnail: "/formal-agreement-signing.png",
    description: "A template for creating comprehensive investment memos for potential deals.",
    author: "Investment Team at GrowthLab",
    date: "Apr 10, 2025",
    readTime: "10 min setup",
    categories: ["Investment", "Documentation"],
    topics: ["Investment Thesis", "Deal Analysis", "Portfolio Management"],
    featured: false,
    popular: true,
    targetAudience: ["investors"],
  },
  {
    id: "investor-template-2",
    title: "Portfolio Company Tracking Template",
    type: "template",
    format: "xlsx",
    thumbnail: "/data-insights-growth.png",
    description: "A template for tracking the performance of your portfolio companies.",
    author: "Portfolio Management Team at GrowthLab",
    date: "Apr 5, 2025",
    readTime: "15 min setup",
    categories: ["Portfolio Management", "Analytics"],
    topics: ["Performance Tracking", "Metrics", "Reporting"],
    featured: false,
    popular: true,
    targetAudience: ["investors"],
  },
  {
    id: "investor-video-1",
    title: "Valuation Methodologies for Early-Stage Startups",
    type: "video",
    format: "mp4",
    thumbnail: "/growth-funding.png",
    description: "Different approaches to valuing pre-revenue and early-stage startups.",
    author: "Valuation Team at GrowthLab",
    date: "Apr 18, 2025",
    readTime: "40 min watch",
    categories: ["Valuation", "Investment"],
    topics: ["Valuation Methods", "Cap Tables", "Term Sheets"],
    featured: true,
    popular: true,
    targetAudience: ["investors"],
  },
  {
    id: "investor-webinar-1",
    title: "Angel Investing Masterclass",
    type: "webinar",
    format: "mp4",
    thumbnail: "/growth-sprout-funding.png",
    description: "A comprehensive guide to angel investing for new and experienced investors.",
    author: "Angel Investor Network at GrowthLab",
    date: "Apr 12, 2025",
    readTime: "90 min watch",
    categories: ["Angel Investing", "Investment"],
    topics: ["Deal Flow", "Investment Strategy", "Portfolio Construction"],
    featured: true,
    popular: false,
    targetAudience: ["investors"],
  },
]
