export const mockPosts = [
  {
    id: "1",
    author: {
      id: "user1",
      displayName: "Sarah Chen",
      avatarUrl: "/abstract-colorful-swirls.png",
      designation: "Founder & CEO at TechNova",
      isVerified: true,
    },
    content:
      "Excited to announce that TechNova has secured $5M in seed funding! 🚀 Looking forward to expanding our team and accelerating product development.",
    createdAt: "2023-05-15T10:30:00Z",
    likesCount: 245,
    commentsCount: 42,
    sharesCount: 18,
    isLiked: false,
    isSaved: false,
    visibility: "public",
    hashtags: ["funding", "startup", "techinnovation"],
    attachments: [
      {
        type: "image",
        url: "/rising-tide-startups.png",
        title: "TechNova Funding Announcement",
      },
    ],
  },
  {
    id: "2",
    author: {
      id: "user2",
      displayName: "Alex Wong",
      avatarUrl: "/abstract-geometric-aw.png",
      designation: "Product Manager at GrowthLab",
      isVerified: false,
    },
    content:
      "Just published our latest report on the Singapore startup ecosystem. Check it out and let me know your thoughts!",
    createdAt: "2023-05-14T15:45:00Z",
    likesCount: 87,
    commentsCount: 23,
    sharesCount: 31,
    isLiked: true,
    isSaved: true,
    visibility: "connections",
    hashtags: ["startupsg", "ecosystem", "report"],
    attachments: [
      {
        type: "link",
        url: "https://example.com/singapore-startup-report",
        title: "Singapore Startup Ecosystem Report 2023",
        description:
          "Comprehensive analysis of funding trends, emerging sectors, and growth opportunities in Singapore's vibrant startup ecosystem.",
        image: "/singapore-startup-collaboration.png",
      },
    ],
  },
  {
    id: "3",
    author: {
      id: "user3",
      displayName: "Enterprise Singapore",
      avatarUrl: "/enterprise-singapore-building.png",
      designation: "Government Agency",
      isVerified: true,
    },
    content:
      "We're launching a new grant program for early-stage startups in the fintech and sustainability sectors. Applications open next week!",
    createdAt: "2023-05-13T09:15:00Z",
    likesCount: 312,
    commentsCount: 78,
    sharesCount: 124,
    isLiked: false,
    isSaved: true,
    visibility: "public",
    isFeatured: true,
    hashtags: ["funding", "fintech", "sustainability", "startupsg"],
    attachments: [],
  },
  {
    id: "4",
    author: {
      id: "user4",
      displayName: "Michelle Tan",
      avatarUrl: "/abstract-ms-flow.png",
      designation: "Venture Partner at SG Innovate",
      isVerified: true,
    },
    content: "What skills do you think are most important for first-time founders? Vote below!",
    createdAt: "2023-05-12T14:20:00Z",
    likesCount: 189,
    commentsCount: 56,
    sharesCount: 12,
    isLiked: false,
    isSaved: false,
    visibility: "public",
    hashtags: ["startupadvice", "founders"],
    poll: {
      question: "Most important skill for first-time founders?",
      options: [
        { text: "Technical expertise", votes: 245 },
        { text: "Sales & marketing", votes: 189 },
        { text: "Financial acumen", votes: 132 },
        { text: "Leadership & team building", votes: 387 },
      ],
      totalVotes: 953,
      daysLeft: 2,
    },
  },
  {
    id: "5",
    author: {
      id: "user5",
      displayName: "David Kumar",
      avatarUrl: "/abstract-geometric-dk.png",
      designation: "CTO at FinFlow",
      isVerified: false,
    },
    content: "Just released our new API documentation. Developers, we'd love your feedback!",
    createdAt: "2023-05-11T11:10:00Z",
    likesCount: 76,
    commentsCount: 18,
    sharesCount: 5,
    isLiked: false,
    isSaved: false,
    visibility: "connections",
    hashtags: ["developers", "api", "fintech"],
    attachments: [
      {
        type: "document",
        name: "FinFlow API Documentation v2.1.pdf",
        size: "3.2 MB",
      },
    ],
  },
  {
    id: "6",
    author: {
      id: "user6",
      displayName: "Singapore Startup Hub",
      avatarUrl: "/singapore-startup-collaboration.png",
      designation: "Community Organization",
      isVerified: true,
    },
    content:
      "Our annual startup conference is back! Join us for three days of workshops, networking, and pitching opportunities. Early bird tickets available now.",
    createdAt: "2023-05-10T08:30:00Z",
    likesCount: 421,
    commentsCount: 97,
    sharesCount: 215,
    isLiked: true,
    isSaved: true,
    visibility: "public",
    isFeatured: true,
    hashtags: ["startupsg", "conference", "networking"],
    attachments: [
      {
        type: "image",
        url: "/startup-demo-day.png",
        title: "Singapore Startup Conference 2023",
      },
    ],
  },
  {
    id: "7",
    author: {
      id: "user7",
      displayName: "Michael Lee",
      avatarUrl: "/abstract-geometric-ts.png",
      designation: "Angel Investor",
      isVerified: true,
    },
    content:
      "Looking to invest in early-stage B2B SaaS startups in Southeast Asia. DM me if you're raising a seed round.",
    createdAt: "2023-05-09T16:45:00Z",
    likesCount: 312,
    commentsCount: 87,
    sharesCount: 45,
    isLiked: false,
    isSaved: false,
    visibility: "public",
    hashtags: ["investing", "venturecapital", "seedfunding", "saas"],
    attachments: [],
  },
  {
    id: "8",
    author: {
      id: "user8",
      displayName: "AI Singapore",
      avatarUrl: "/AI-Healthcare-Integration.png",
      designation: "Government Initiative",
      isVerified: true,
    },
    content:
      "Applications for our AI Apprenticeship Programme are now open! Looking for talented individuals passionate about AI and machine learning.",
    createdAt: "2023-05-08T10:15:00Z",
    likesCount: 287,
    commentsCount: 64,
    sharesCount: 93,
    isLiked: false,
    isSaved: false,
    visibility: "public",
    isFeatured: true,
    hashtags: ["artificialintelligence", "machinelearning", "careers", "singapore"],
    attachments: [
      {
        type: "link",
        url: "https://example.com/ai-apprenticeship",
        title: "AI Apprenticeship Programme 2023",
        description: "A 9-month programme to train and develop AI talent in Singapore.",
        image: "/machine-learning-concept.png",
      },
    ],
  },
  {
    id: "9",
    author: {
      id: "user9",
      displayName: "Green Path Logistics",
      avatarUrl: "/green-path-logistics.png",
      designation: "Sustainable Logistics Startup",
      isVerified: false,
    },
    content:
      "Proud to announce that we've reduced our carbon footprint by 35% this quarter through our new electric fleet and route optimization algorithms.",
    createdAt: "2023-05-07T13:20:00Z",
    likesCount: 156,
    commentsCount: 28,
    sharesCount: 42,
    isLiked: true,
    isSaved: false,
    visibility: "public",
    hashtags: ["sustainability", "logistics", "climateaction"],
    attachments: [
      {
        type: "image",
        url: "/green-tractor-field.png",
        title: "Green Path Logistics Electric Fleet",
      },
    ],
  },
  {
    id: "10",
    author: {
      id: "user10",
      displayName: "Lisa Tan",
      avatarUrl: "/abstract-geometric-ll.png",
      designation: "Growth Marketer",
      isVerified: false,
    },
    content:
      'Just published a new blog post on "10 Growth Hacking Strategies for Early-Stage Startups". Check it out and let me know what you think!',
    createdAt: "2023-05-06T09:45:00Z",
    likesCount: 98,
    commentsCount: 31,
    sharesCount: 24,
    isLiked: false,
    isSaved: true,
    visibility: "connections",
    hashtags: ["growthhacking", "marketing", "startups"],
    attachments: [
      {
        type: "link",
        url: "https://example.com/growth-hacking-strategies",
        title: "10 Growth Hacking Strategies for Early-Stage Startups",
        description: "Learn how to grow your startup with limited resources using these proven strategies.",
        image: "/financial-projection-growth.png",
      },
    ],
  },
]
