/**
 * Additional startup-specific resources
 *
 * These resources are specifically designed for early-stage and
 * growth-stage startups without changing any UI/UX components.
 */

export const startupSpecificResources = [
  {
    id: "startup-guide-1",
    title: "Minimum Viable Product Development Guide",
    type: "guide",
    format: "pdf",
    thumbnail: "/product-manager-brainstorm.png",
    description: "A practical guide to building and launching your MVP with limited resources.",
    author: "Product Team at GrowthLab",
    date: "Apr 18, 2025",
    readTime: "25 min read",
    categories: ["Product", "Development"],
    topics: ["MVP", "Product Development", "User Testing"],
    featured: true,
    popular: true,
    targetAudience: ["startups"],
  },
  {
    id: "startup-guide-2",
    title: "Customer Acquisition on a Budget",
    type: "guide",
    format: "pdf",
    thumbnail: "/marketing-professional.png",
    description: "Cost-effective strategies for acquiring your first 1,000 customers.",
    author: "Growth Team at GrowthLab",
    date: "Apr 10, 2025",
    readTime: "20 min read",
    categories: ["Marketing", "Growth"],
    topics: ["Customer Acquisition", "Growth Hacking", "Marketing Strategy"],
    featured: false,
    popular: true,
    targetAudience: ["startups"],
  },
  {
    id: "startup-template-1",
    title: "Startup Financial Model Template",
    type: "template",
    format: "xlsx",
    thumbnail: "/financial-projection-growth.png",
    description: "A comprehensive financial model template for startups with 3-year projections.",
    author: "Finance Team at GrowthLab",
    date: "Apr 15, 2025",
    readTime: "15 min setup",
    categories: ["Finance", "Planning"],
    topics: ["Financial Modeling", "Projections", "Cash Flow"],
    featured: true,
    popular: true,
    targetAudience: ["startups"],
  },
  {
    id: "startup-template-2",
    title: "Go-to-Market Strategy Template",
    type: "template",
    format: "pptx",
    thumbnail: "/interconnected-marketing-network.png",
    description: "A template for planning your product launch and go-to-market strategy.",
    author: "Marketing Team at GrowthLab",
    date: "Apr 5, 2025",
    readTime: "12 min setup",
    categories: ["Marketing", "Strategy"],
    topics: ["GTM", "Product Launch", "Market Entry"],
    featured: false,
    popular: true,
    targetAudience: ["startups"],
  },
  {
    id: "startup-video-1",
    title: "Startup Tech Stack Selection",
    type: "video",
    format: "mp4",
    thumbnail: "/software-engineer-workspace.png",
    description: "How to choose the right technology stack for your startup.",
    author: "CTO at GrowthLab",
    date: "Apr 12, 2025",
    readTime: "35 min watch",
    categories: ["Technology", "Development"],
    topics: ["Tech Stack", "Architecture", "Scalability"],
    featured: true,
    popular: false,
    targetAudience: ["startups"],
  },
  {
    id: "startup-webinar-1",
    title: "Navigating Startup Pivots",
    type: "webinar",
    format: "mp4",
    thumbnail: "/strategic-project-journey.png",
    description: "When and how to pivot your startup with real-world case studies.",
    author: "Strategy Team at GrowthLab",
    date: "Apr 8, 2025",
    readTime: "60 min watch",
    categories: ["Strategy", "Pivoting"],
    topics: ["Business Model", "Market Fit", "Strategic Decisions"],
    featured: false,
    popular: true,
    targetAudience: ["startups"],
  },
]
