/**
 * Additional student-specific resources
 *
 * These resources are specifically designed for students
 * without changing any UI/UX components.
 */

export const studentSpecificResources = [
  {
    id: "student-guide-1",
    title: "Student Entrepreneur's Handbook",
    type: "guide",
    format: "pdf",
    thumbnail: "/tech-professional.png",
    description: "A comprehensive guide for students looking to start a business while studying.",
    author: "Education Team at GrowthLab",
    date: "Apr 22, 2025",
    readTime: "35 min read",
    categories: ["Student Entrepreneurship", "Education"],
    topics: ["Time Management", "University Resources", "Student Startups"],
    featured: true,
    popular: true,
    targetAudience: ["students"],
  },
  {
    id: "student-guide-2",
    title: "From Classroom to Startup: Academic Project Commercialization",
    type: "guide",
    format: "pdf",
    thumbnail: "/collaborative-prototype-session.png",
    description: "How to turn your academic projects into viable business ventures.",
    author: "Innovation Team at GrowthLab",
    date: "Apr 15, 2025",
    readTime: "25 min read",
    categories: ["Innovation", "Commercialization"],
    topics: ["IP Rights", "University Spinoffs", "Research Commercialization"],
    featured: false,
    popular: true,
    targetAudience: ["students"],
  },
  {
    id: "student-template-1",
    title: "Student Startup Business Plan Template",
    type: "template",
    format: "docx",
    thumbnail: "/diverse-group.png",
    description: "A business plan template designed specifically for student entrepreneurs.",
    author: "Education Team at GrowthLab",
    date: "Apr 18, 2025",
    readTime: "10 min setup",
    categories: ["Business Planning", "Student Entrepreneurship"],
    topics: ["Business Plan", "Student Startups", "Planning"],
    featured: true,
    popular: false,
    targetAudience: ["students"],
  },
  {
    id: "student-template-2",
    title: "Startup Competition Pitch Deck Template",
    type: "template",
    format: "pptx",
    thumbnail: "/startup-pitch-competition.png",
    description: "A pitch deck template designed for university startup competitions.",
    author: "Pitch Team at GrowthLab",
    date: "Apr 10, 2025",
    readTime: "15 min setup",
    categories: ["Pitching", "Competitions"],
    topics: ["Pitch Deck", "Startup Competitions", "Presentation"],
    featured: false,
    popular: true,
    targetAudience: ["students"],
  },
  {
    id: "student-video-1",
    title: "Balancing Studies and Startup: Student Founder Stories",
    type: "video",
    format: "mp4",
    thumbnail: "/diverse-professional-profiles.png",
    description: "Successful student entrepreneurs share their experiences and advice.",
    author: "Student Founders Network at GrowthLab",
    date: "Apr 20, 2025",
    readTime: "45 min watch",
    categories: ["Student Entrepreneurship", "Case Studies"],
    topics: ["Student Founders", "Work-Life Balance", "Success Stories"],
    featured: true,
    popular: true,
    targetAudience: ["students"],
  },
  {
    id: "student-webinar-1",
    title: "University Resources for Student Entrepreneurs",
    type: "webinar",
    format: "mp4",
    thumbnail: "/smart-learning-tools.png",
    description: "How to leverage university resources, incubators, and accelerators.",
    author: "University Relations Team at GrowthLab",
    date: "Apr 15, 2025",
    readTime: "60 min watch",
    categories: ["University Resources", "Student Entrepreneurship"],
    topics: ["Incubators", "Accelerators", "University Support"],
    featured: false,
    popular: true,
    targetAudience: ["students"],
  },
]
